name: Translate README

on:
  push:
    branches:
      - main

env:
  # Definimos los idiomas como array en formato JSON
  TRANSLATION_LANGS: '["es", "pt", "fr"]'

jobs:
  prepare-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update main README with translation links
        env:
          # Pasamos la variable a formato shell
          LANGS_STRING: ${{ fromJSON(env.TRANSLATION_LANGS) }}
        run: |
          echo -e "## README Translations\n" > README.translations.md
          echo "- [English](README.md)" >> README.translations.md
          
          # Convertimos el JSON a array en bash
          LANGS_ARRAY=($(echo '$LANGS_STRING' | jq -r '.[]'))
          
          for lang in "${LANGS_ARRAY[@]}"; do
            echo "- [$(echo $lang | tr 'a-z' 'A-Z')](README.$lang.md)" >> README.translations.md
          done
          
          cat README.md README.translations.md > README.combined.md
          mv README.combined.md README.md
          rm README.translations.md
          
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Add translation links to README" || echo "No changes to commit"
          git push

  translate:
    needs: prepare-readme
    runs-on: ubuntu-latest
    strategy:
      matrix:
        languages: ${{ fromJSON(env.TRANSLATION_LANGS) }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Translate to ${{ matrix.languages }}
        uses: dephraiim/translate-readme@main
        with:
          LANG: ${{ matrix.languages }}